config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  root 'users#index'
  resources :users
  resources :indicators
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chance.rb
# == Schema Information
#
# Table name: chances
#
#  id                    :integer          not null, primary key
#  kredit_kes            :integer
#  kredit_refinansiranje :integer
#  kredit_stambeni       :integer
#  kredit_auto           :integer
#  kredit_evergrin       :integer
#  kredit_fluo           :integer
#  kredit_potrosacki     :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  user_id               :integer
#

class Chance < ApplicationRecord
  belongs_to :user
  has_many :factors
end

app/models/factor.rb
# == Schema Information
#
# Table name: factors
#
#  id         :integer          not null, primary key
#  chance_id  :integer
#  title      :string
#  amount     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Factor < ApplicationRecord
  belongs_to :chance
end

app/models/indicator.rb
# == Schema Information
#
# Table name: indicators
#
#  id         :integer          not null, primary key
#  product    :string
#  name       :string
#  score      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Indicator < ApplicationRecord
end

app/models/loan.rb
# == Schema Information
#
# Table name: loans
#
#  id                  :integer          not null, primary key
#  loan_type           :string
#  purchase_date       :date
#  status              :string
#  amount              :integer
#  repayment           :date
#  interest_rate       :decimal(, )
#  administrative_cost :decimal(, )
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :integer
#

class Loan < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  client_id  :integer
#  name       :string
#  surname    :string
#  birthdate  :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  has_many :loans
  has_one :chance, inverse_of: :user, dependent: :destroy
  accepts_nested_attributes_for :chance, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
  before_action :set_indicator, only: [:show, :edit, :update, :destroy]

  # GET /indicators
  # GET /indicators.json
  def index
    @indicators = Indicator.all
    @indicator = Indicator.new
  end

  # GET /indicators/1
  # GET /indicators/1.json
  def show
  end

  # GET /indicators/new
  def new
    @indicator = Indicator.new
  end

  # GET /indicators/1/edit
  def edit
  end

  # POST /indicators
  # POST /indicators.json
  def create
    @indicator = Indicator.new(indicator_params)

    respond_to do |format|
      if @indicator.save
        update_indicators
        format.html { redirect_to indicators_path, notice: 'Indicator was successfully created.' }
        format.json { render :show, status: :created, location: @indicator }
      else
        format.html { render :new }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicators/1
  # PATCH/PUT /indicators/1.json
  def update
    respond_to do |format|
      if @indicator.update(indicator_params)
        update_indicators
        format.html { redirect_to indicators_path, notice: 'Indicator was successfully updated.' }
        format.json { render :show, status: :ok, location: @indicator }
      else
        format.html { render :edit }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicators/1
  # DELETE /indicators/1.json
  def destroy
    @indicator.destroy
    respond_to do |format|
      format.html { redirect_to indicators_url, notice: 'Indicator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def update_indicators
      Indicator.where(status: 'new').each do |indicator|
        url = "http://40e0f9fb.ngrok.io/addIndicator" +
          "?type=like" +
          "&product=#{indicator.product}" +
          "&name=#{indicator.name}" +
          "&score=#{indicator.score}"

        begin
          factor = open(url).read.to_f

          if factor != 0
            factor = (factor * 100).to_i
            User.all.each do |user|
              if (indicator.product == 'Stambeni')
                Factor.create!(chance: user.chance, product: indicator.product, title: "Liked #{indicator.name}", amount: factor)
                user.chance.update!(kredit_stambeni: user.chance.kredit_stambeni + factor)
              elsif (indicator.product == 'Auto')
                Factor.create!(chance: user.chance, product: indicator.product, title: "Liked #{indicator.name}", amount: factor)
                user.chance.update!(kredit_auto: user.chance.kredit_auto + factor)
              elsif (indicator.product == 'Keš')
                Factor.create!(chance: user.chance, product: indicator.product, title: "Liked #{indicator.name}", amount: factor)
                user.chance.update!(kredit_kes: user.chance.kredit_kes + factor)
              elsif (indicator.product == 'Evergrin')
                Factor.create!(chance: user.chance, product: indicator.product, title: "Liked #{indicator.name}", amount: factor)
                user.chance.update!(kredit_evergrin: user.chance.kredit_evergrin + factor)
              elsif (indicator.product == 'Fluo')
                Factor.create!(chance: user.chance, product: indicator.product, title: "Liked #{indicator.name}", amount: factor)
                user.chance.update!(kredit_fluo: user.chance.kredit_fluo + factor)
              elsif (indicator.product == 'Potrošački')
                Factor.create!(chance: user.chance, product: indicator.product, title: "Liked #{indicator.name}", amount: factor)
                user.chance.update!(kredit_potrosacki: user.chance.kredit_potrosacki + factor)
              end
            end
          end

          indicator.update!(status: 'old')
        rescue
        end
      end

    end

    # Use callbacks to share common setup or constraints between actions.
    def set_indicator
      @indicator = Indicator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicator_params
      params.require(:indicator).permit(:product, :name, :score, :status)
    end
end

app/controllers/users_controller.rb
require 'open-uri'

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @chance = @user.chance
    @loans = @user.loans.order(purchase_date: :desc)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/indicators_helper.rb
module IndicatorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/indicators/_form.html.haml
= bootstrap_form_for @indicator do |f|
  - if @indicator.errors.any?
    #error_explanation
      %h2= "#{pluralize(@indicator.errors.count, "error")} prohibited this indicator from being saved:"
      %ul
        - @indicator.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    %label Društvena Akcija
    %select.form-control
      %option Like
      %option Life event
      %option Group join
      %option Event attendance
      %option Travel

  / = f.text_field :product, label: "Proizvod"
  = f.select :product, [['Stambeni', "Stambeni"], ['Auto', 'Auto'], ['Fluo', 'Fluo'], ['Evergrin', 'Evergrin'], ['Potrošački', 'Potrošački']], { label: "Proizvod" }, { class: "selectpicker" }
  = f.text_field :name, label: "Facebook stranica"
  = f.text_field :score, label: "Težina"
  = f.hidden_field :status, value: 'new'
  = f.submit 'Dodaj indikator', class: 'btn btn-success'

app/views/indicators/edit.html.haml
%h1 Editing indicator

= render 'form'

= link_to 'Show', @indicator
\|
= link_to 'Back', indicators_path

app/views/indicators/index.html.haml
/ page content
.right_col{:role => "main"}
  %div
    .page-title
      .title_left
        %h3
          Indikatori

    .clearfix
    .row
      .col-md-12.col-sm-12.col-xs-12
        .x_panel
          .x_title

            %table#datatable.table.table-striped.table-bordered
              %thead
                %tr
                  %th Targetovani proizvod
                  %th Facebook stranica
                  %th Score
                  / %th
                  / %th
                  / %th

              %tbody
                - @indicators.each do |indicator|
                  %tr
                    %td= indicator.product
                    %td= indicator.name
                    %td= indicator.score
                    / %td= link_to 'Show', indicator
                    / %td= link_to 'Edit', edit_indicator_path(indicator)
                    / %td= link_to 'Destroy', indicator, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %button.btn.btn.btn-success{"data-target" => "#indicator", "data-toggle" => "modal", type: "button"} Dodaj indikator

  #indicator.modal.fade{"aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#myModalLabel.modal-title Dodaj indikator
        .modal-body{style: 'font-size: 120%;'}
          = render 'form'

app/views/indicators/new.html.haml
%h1 New indicator

= render 'form'

= link_to 'Back', indicators_path

app/views/indicators/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @indicator.product
%p
  %b Name:
  = @indicator.name
%p
  %b Score:
  = @indicator.score

= link_to 'Edit', edit_indicator_path(@indicator)
\|
= link_to 'Back', indicators_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SocieteGeneraleFintechHackathonDashboard
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.nav-md
    .container.body
      .main_container
        .col-md-3.left_col
          .left_col.scroll-view
            .navbar.nav_title{:style => "border: 0;"}
              %a.site_title
                %span SG Hackboard
            .clearfix
            / menu profile quick info
            .profile.clearfix
              .profile_pic
                = image_tag 'sg.png', class: 'img-circle profile_img'
              .profile_info
                %span Welcome,
                %h2 SG Admin
            / /menu profile quick info
            %br/
            / sidebar menu
            #sidebar-menu.main_menu_side.hidden-print.main_menu
              .menu_section
                %h3 Kontrolni panel
                %ul.nav.side-menu
                  %li
                    = link_to root_path do
                      %i.fa.fa-home
                      Svi klijenti

                  %li
                    = link_to indicators_path do
                      %i.fa.fa-list
                      Indikatori

        = yield



        / footer content
        %footer
          .pull-right
            SG Hackboard
          .clearfix
        / /footer content

app/views/users/_chance.haml
/ Chance
.col-sm-4.col-xs-12.widget.widget_tally_box
  %button.x_panel.ui-ribbon-container.fixed_height_390{"data-target" => "#contact", "data-toggle" => "modal", :type => "button"}
    - if percent > 75
      .ui-ribbon-wrapper
        .ui-ribbon
          Prioritet
    / .x_title
    /   %h2= type
    /   .clearfix
    .x_content
      %div{style: "text-align: center; margin-bottom: 17px"}
        %span.chart{"data-percent" => percent}
          %span.percent= percent
          %canvas{height: "110", width: "110"}
      %h3.name_title= "#{name} #{type}"

      %br
      %div
        %ul.list-inline.widget_tally
          - @chance.factors.where(product: name).order(id: :desc).limit(3).each do |factor|
            %li
              %span.month
                - if factor.title.include? 'kredit'
                  %i.fa.fa-bar-chart{style: "color: #3b5998;"}
                - else
                  %i.fa.fa-facebook-official{style: "color: #3b5998;"}
                = factor.title
              %span.count
                = factor.amount > 0 ? '+' : '-'
                = "#{factor.amount.abs}%"
      / %p Šansa za kupovinu
      / .divider
      / %p If you've decided to go in development mode and tweak all of this a bit, there are few things you should do.

app/views/users/index.html.haml
/ page content
.right_col{:role => "main"}
  %div
    .page-title
      .title_left
        %h3
          Svi klijenti

    .clearfix
    .row
      .col-md-12.col-sm-12.col-xs-12
        .x_panel
          .x_title

            %table#datatable.table.table-striped.table-bordered
              %thead
                %tr
                  %th Korisnik
                  / %th Rođen
                  %th Keš
                  %th Refinansiranje
                  %th Stambeni
                  %th Auto
                  %th Evergrin
                  %th Fluo
                  %th Potrošački

              %tbody
                - @users.each do |user|
                  %tr
                    %td= link_to "#{user.name} #{user.surname}", user_path(user)
                    / %td= user.birthdate
                    %td= "#{user.chance.kredit_kes}%"
                    %td= "#{user.chance.kredit_refinansiranje}%"
                    %td= "#{user.chance.kredit_stambeni}%"
                    %td= "#{user.chance.kredit_auto}%"
                    %td= "#{user.chance.kredit_evergrin}%"
                    %td= "#{user.chance.kredit_fluo}%"
                    %td= "#{user.chance.kredit_potrosacki}%"


  #contact.modal.fade{"aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#myModalLabel.modal-title Kontaktiraj klijenta
        .modal-body{style: 'font-size: 120%;'}
          %button.btn.btn-lg.btn-success{type: "button"} Pošalji SMS
          %i.fa.fa-android
          / = @user.name
          preferira SMS komunikaciju.
          %br
          %button.btn.btn-lg.btn-success{type: "button"} Pošalji email
          %br
          %button.btn.btn-lg.btn-success{type: "button"} Pozovi

app/views/users/show.html.haml
/ /top navigation
/ page content
.right_col{:role => "main"}

  .x_content{style: 'margin-top: 30px;'}
  .row
    .col-md-4.col-sm-4.col-xs-12.profile_left
      / .profile_img
      /   #crop-avatar
      /     / Current avatar
      /     %img.img-responsive.avatar-view{:alt => "Avatar", :src => "https://colorlib.com/polygon/gentelella/images/picture.jpg", :title => "Change the avatar"}/
      %h3= "#{@user.name} #{@user.surname}"
      / %ul.list-unstyled.user_data
      /   %li
      /     %i.fa.fa-map-marker.user-profile-icon
      /     San Francisco, California, USA
      /   %li
      /     %i.fa.fa-briefcase.user-profile-icon
      /     Software Engineer

      %br

      .x_panel
        .x_title
          %h2
            Prethodne kupovine
          .clearfix
        .x_content
          %ul.list-unstyled.timeline
            - @loans.each do |loan|
              %li
                .block
                  .tags
                    .tag
                      %span= loan.purchase_date
                  .block_content
                    %h2.title
                      = loan.loan_type
                    .byline
                      %span.label.label-warning= loan.status

                    %p.excerpt
                      Kamatna stopa:
                      %strong= "#{loan.interest_rate}%"
                      %br

                      Administrativni troškovi:
                      %strong= "#{loan.administrative_cost}%"

                      %br
                      Rok otplate:
                      %strong= loan.repayment


    .col-md-8.col-sm-8.col-xs-12
      %h3 Šanse za kupovinu
      %br
      .row
        = render 'chance', type: 'Kredit', name: 'Stambeni', percent: @chance.kredit_stambeni
        = render 'chance', type: 'Kredit', name: 'Auto', percent: @chance.kredit_auto
        = render 'chance', type: 'Kredit', name: 'Keš', percent: @chance.kredit_kes
        = render 'chance', type: 'Kredit', name: 'Potrošački', percent: @chance.kredit_potrosacki
        = render 'chance', type: 'Kredit', name: 'Fluo', percent: @chance.kredit_fluo
        = render 'chance', type: 'Kredit', name: 'Evergrin', percent: @chance.kredit_evergrin

        / = render 'chance', type: 'Kreditne kartice', name: 'Masterata', percent: 2
        / = render 'chance', type: 'Kreditne kartice', name: 'Visa gold', percent: 30

        / = render 'chance', type: 'Osiguranje', name: 'Životno', percent: 67
        / = render 'chance', type: 'Osiguranje', name: 'Štedno životno', percent: 72
        / = render 'chance', type: 'Osiguranje', name: 'Putno', percent: 50
        / = render 'chance', type: 'Osiguranje', name: 'Imovinsko', percent: 68
        / = render 'chance', type: 'Osiguranje', name: 'Zdravstveno', percent: 91

  #contact.modal.fade{"aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#myModalLabel.modal-title Kontaktiraj klijenta
        .modal-body{style: 'font-size: 120%;'}
          %button.btn.btn-lg.btn-success{type: "button"} Pošalji SMS
          %i.fa.fa-android
          = @user.name
          preferira SMS komunikaciju.
          %br
          %button.btn.btn-lg.btn-success{type: "button"} Pošalji email
          %br
          %button.btn.btn-lg.btn-success{type: "button"} Pozovi